Minor enhancements
Add config file
Merge xfsu into xfsudo
Update documentation

diff --git a/bin/xfsudo b/bin/xfsudo
--- a/bin/xfsudo
+++ b/bin/xfsudo
@@ -1,7 +1,28 @@
 #!/bin/bash
-pass="$(zenity --title='xfsudo' --password)"
-if [ ! "$pass" == "" ]; then
-	echo "$pass" | sudo -Sk env HOME=$HOME "$@"
-else
-	exit 1
+# xfsudo: run as root using sudo
+
+## Default mode
+mode=sudo  # run with root priviliges and user's environment variables
+#mode=root  # run with root priviliges and root's environment variables
+
+# Config file which will override above setting
+if [ -f /etc/xfsudo.conf ]; then
+	source /etc/xfsudo.conf
 fi
+
+# Get the password
+pass="$(zenity --title='xfsudo' --password)"
+
+# Check if password is empty
+if [ "$pass" == "" ]; then
+	$(zenity --title='xfsudo' --error --text='Password not entered') && exit 1
+fi
+
+# Pass the password and command-line arguments to sudo
+if [ "$mode" == "sudo" ]; then
+	echo "$pass" | sudo -Sk env HOME=$HOME "$@" || $(zenity --title='xfsudo' --error --text='Incorrect password entered')
+else
+	echo "$pass" | sudo -Sik "$@" || $(zenity --title='xfsudo' --error --text='Incorrect password entered')
+fi
+
+exit 0
